version: "3.9"

services:
  online-spy:
    build: .
    container_name: online-spy
    image: online-spy
    restart: always
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
    networks:
      - network1

  postgres:
    image: postgres:15
    container_name: online-spy-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - network1

volumes:
  postgres_data:

networks:
  network1:
    name: my-network
